"""Walk dnsight's Click tree and write docs/cli pages plus _generated_nav.json.

MkDocs loads :mod:`tools.docgen.hooks` (see repo ``mkdocs.yml``) to splice
``_generated_nav.json`` into the site nav at build time.

Top-level nav grouping (see also module constants):

- **General** (no nav section title — peer links): ``version``, ``docs``, ``config``.
- **Audit**: ``audit`` only.
- **Checks**: every other direct child of the root group.

New CLI commands default into **Checks** unless added to ``GENERAL_COMMANDS`` or
``AUDIT_COMMANDS``.
"""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any

import click
from typer.main import get_command

from dnsight.cli.main import app


__all__ = ["main"]

DOCS_CLI = Path("docs/cli")
GENERATED_NAV_PATH = DOCS_CLI / "_generated_nav.json"
BANNER = "<!-- AUTO-GENERATED by tools/docgen — do not edit -->\n\n"

GENERAL_COMMANDS: frozenset[str] = frozenset({"version", "docs", "config"})
# Nav and root index list general commands in this order (not alphabetical).
_GENERAL_ORDER: tuple[str, ...] = ("version", "docs", "config")
AUDIT_COMMANDS: frozenset[str] = frozenset({"audit"})
_SKIP_ROOT_PARAM_NAMES: frozenset[str] = frozenset(
    {"install_completion", "show_completion"}
)


def main() -> None:
    root = get_command(app)
    if not isinstance(root, click.Group):
        msg = "Expected root Typer to compile to a Click Group."
        raise TypeError(msg)
    DOCS_CLI.mkdir(parents=True, exist_ok=True)
    _walk_and_emit(root, (), root)
    nav = _build_cli_nav(root)
    GENERATED_NAV_PATH.write_text(
        json.dumps(nav, indent=2, ensure_ascii=True) + "\n", encoding="utf-8"
    )


def _walk_and_emit(
    node: click.Command, path: tuple[str, ...], root: click.Group
) -> None:
    _emit_markdown(path, node, root)
    if isinstance(node, click.Group):
        for name in sorted(node.commands):
            sub = node.commands[name]
            _walk_and_emit(sub, path + (name,), root)


def _md_path(path: tuple[str, ...]) -> Path:
    if not path:
        return DOCS_CLI / "index.md"
    return DOCS_CLI.joinpath(*path) / "index.md"


def _append_options_md(parts: list[str], node: click.Command) -> None:
    params = [
        p
        for p in node.params
        if not getattr(p, "hidden", False) and p.name not in _SKIP_ROOT_PARAM_NAMES
    ]
    if not params:
        return
    parts.append("## Options\n\n")
    parts.append("| Option | Type | Default | Required | Description |\n")
    parts.append("| --- | --- | --- | --- | --- |\n")
    for p in params:
        parts.append(_format_param_row(p) + "\n")
    parts.append("\n")


def _append_subcommands_md(parts: list[str], node: click.Command) -> None:
    if not isinstance(node, click.Group) or not node.commands:
        return
    parts.append("## Subcommands\n\n")
    parts.append("| Command | Description |\n")
    parts.append("| --- | --- |\n")
    for name in sorted(node.commands):
        sub = node.commands[name]
        desc = (sub.short_help or sub.help or "—").split("\n")[0]
        desc = desc.replace("|", "\\|")
        rel = f"{name}/index.md"
        parts.append(f"| [`{name}`]({rel}) | {desc} |\n")
    parts.append("\n")


def _write_cli_doc(rel: Path, content: str) -> None:
    """Write *content* to *rel* only when it resolves under ``DOCS_CLI``."""
    base = DOCS_CLI.resolve()
    target = rel.resolve()
    if not target.is_relative_to(base):
        msg = f"CLI doc output outside docs/cli tree: {rel}"
        raise ValueError(msg)
    target.parent.mkdir(parents=True, exist_ok=True)
    with target.open("w", encoding="utf-8") as fh:
        fh.write(content)


def _emit_markdown(
    path: tuple[str, ...], node: click.Command, root: click.Group
) -> None:
    rel = _md_path(path)
    title = "dnsight" if not path else "dnsight " + " ".join(path)
    parts: list[str] = [BANNER, f"# `{title}`\n\n"]
    if node.help:
        parts.append(node.help.strip() + "\n\n")
    if isinstance(node, click.Group):
        ctx_settings = getattr(node, "context_settings", None) or {}
        if ctx_settings.get("no_args_is_help"):
            parts.append(
                "*With no subcommand or arguments, this group shows help "
                "(Click/Typer `no_args_is_help`).*\n\n"
            )
    _append_options_md(parts, node)
    _append_subcommands_md(parts, node)
    epilog = getattr(node, "epilog", None)
    if epilog:
        parts.append("## Epilog\n\n")
        parts.append(epilog.strip() + "\n\n")
    if not path:
        parts.extend(_root_index_sections(root))
    _write_cli_doc(rel, "".join(parts))


def _format_option_cell(p: click.Parameter) -> str:
    """All CLI switches for this parameter (primary and ``--no-*`` / secondary)."""
    names: list[str] = list(getattr(p, "opts", []) or [])
    names.extend(getattr(p, "secondary_opts", []) or ())
    if not names:
        return "—"
    return " / ".join(f"`{n}`" for n in names)


def _format_type_cell(p: click.Parameter) -> str:
    if getattr(p, "is_flag", False):
        return "bool"
    return getattr(p.type, "name", None) or str(p.type)


def _format_flag_default_cell(p: click.Parameter) -> str:
    default_val = p.default
    secondary = getattr(p, "secondary_opts", None) or ()
    if secondary:
        if default_val is None:
            # Tri-state: omitting the flag does not set a value on the CLI; we
            # do not echo dnsight.yaml / schema defaults here (see Configuration).
            return "—"
        if default_val is True:
            return "`true`"
        if default_val is False:
            return "`false`"
        return f"`{default_val!r}`"
    if callable(default_val):
        return "*(callable)*"
    if default_val is None:
        return "—"
    return "`true`" if default_val else "`false`"


def _format_non_flag_default_cell(p: click.Parameter) -> str:
    default_val = p.default
    if callable(default_val):
        return "*(callable)*"
    if default_val is None:
        return "—"
    return f"`{default_val!r}`"


def _format_default_cell(p: click.Parameter) -> str:
    if getattr(p, "is_flag", False):
        return _format_flag_default_cell(p)
    return _format_non_flag_default_cell(p)


def _format_param_row(p: click.Parameter) -> str:
    opts_cell = _format_option_cell(p)
    type_name = _format_type_cell(p)
    default_s = _format_default_cell(p)
    req = "yes" if p.required else "no"
    help_s = (getattr(p, "help", None) or "—").replace("|", "\\|").replace("\n", " ")
    return f"| {opts_cell} | {type_name} | {default_s} | {req} | {help_s} |"


def _root_index_sections(root: click.Group) -> list[str]:
    top = set(root.commands.keys())
    lines: list[str] = ["## Command index\n\n"]
    lines.append("### General\n\n")
    for name in _GENERAL_ORDER:
        if name in top:
            lines.append(f"- [`dnsight {name}`]({name}/index.md)\n")
    lines.append("\n### Audit\n\n")
    for name in sorted(AUDIT_COMMANDS & top):
        lines.append(f"- [`dnsight {name}`]({name}/index.md)\n")
    lines.append("\n### Checks\n\n")
    checks = top - GENERAL_COMMANDS - AUDIT_COMMANDS
    for name in sorted(checks):
        lines.append(f"- [`dnsight {name}`]({name}/index.md)\n")
    lines.append("\n")
    return lines


def _nav_nested(path: tuple[str, ...], group: click.Group) -> list[dict[str, Any]]:
    prefix = "/".join(path)
    items: list[dict[str, Any]] = [{"Overview": f"cli/{prefix}/index.md"}]
    for name in sorted(group.commands):
        sub = group.commands[name]
        sub_path = path + (name,)
        sub_prefix = "/".join(sub_path)
        if isinstance(sub, click.Group):
            items.append({name: _nav_nested(sub_path, sub)})
        else:
            items.append({name: f"cli/{sub_prefix}/index.md"})
    return items


def _nav_leaf_or_group(name: str, cmd: click.Command) -> dict[str, Any]:
    if isinstance(cmd, click.Group):
        return {name: _nav_nested((name,), cmd)}
    return {name: f"cli/{name}/index.md"}


def _build_cli_nav(root: click.Group) -> list[Any]:
    top = set(root.commands.keys())
    nav: list[Any] = [{"Overview": "cli/index.md"}]
    for name in _GENERAL_ORDER:
        if name in top:
            nav.append(_nav_leaf_or_group(name, root.commands[name]))
    if AUDIT_COMMANDS & top:
        nav.append({"Audit": [{"audit": "cli/audit/index.md"}]})
    checks = sorted(top - GENERAL_COMMANDS - AUDIT_COMMANDS)
    nav.append({"Checks": [_nav_leaf_or_group(n, root.commands[n]) for n in checks]})
    return nav
