name: Scan Code
description: Scans code with SonarQube

runs:
  using: composite
  steps:
    - name: SonarQube Scan
      uses: SonarSource/sonarqube-scan-action@a31c9398be7ace6bbfaf30c0bd5d415f843d45e9  # v7.0.0
